apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evmosnode0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard-rwo
status: {}
